### PR TITLE
Allow nested drivers

### PR DESCRIPTION
**Pull request by BlackPhlox**
Allows you to create a nested driver using a derive (`Debug` derive is needed as well due to `RigDriver` in `CameraRig` uses `std::fmt::Debug`), there might be a smarter way to make this abstraction, though I do not know how. Any input is highly appreciated:
```rust
use dolly::{
    driver::RigDriver,
    glam::Vec3,
    prelude::{Arm, CameraRig, LookAt, Position, Rotation, Smooth},
    rig::RigUpdateParams,
    DollyDriver,
};

#[derive(Debug, DollyDriver)]
pub struct Follow {
    pub rig: CameraRig,
}

impl Follow {
    pub fn init(transform: dolly::transform::Transform) -> Self {
        Self {
            rig: CameraRig::builder()
                .with(Position::new(transform.position))
                .with(Rotation::new(transform.rotation))
                .with(Smooth::new_position(1.25).predictive(true))
                .with(Arm::new(Vec3::new(0.0, 1.5, -3.5)))
                .with(Smooth::new_position(2.5))
                .with(
                    LookAt::new(transform.position + Vec3::Y)
                        .tracking_smoothness(1.25)
                        .tracking_predictive(true),
                )
                .build(),
        }
    }

    pub fn update(&mut self, position: Vec3, rotation: dolly::glam::Quat, target: Vec3) {
        self.rig.driver_mut::<Position>().position = position;
        self.rig.driver_mut::<Rotation>().rotation = rotation;
        self.rig.driver_mut::<LookAt>().target = target;
    }
}
```

Allows for:

In setup:
```rust
CameraRig::builder()
.with(Follow::init(
	  dolly::transform::Transform {
		  position: start_pos,
		  rotation: dolly::glam::Quat::IDENTITY,
	  }
)).build()
```
At runtime:
```rust
rig.driver_mut::<Follow>().update(
	player.position,
	player.rotation,
	player.position + Vec3::Y,
);

let transform = rig.update(time.delta_seconds());

```

### CODE REVIEW

**Comment by h3r2tic** [comment]
Hey! Thanks for the ideas here! Now I'm kinda curious how you're using the nested rigs, and how you're composing your cameras 😄

I wonder if we need the macro magic at all... Without it, one can still write the rather simple

```rust
impl RigDriver for Follow {
    fn update(&mut self, params: dolly::rig::RigUpdateParams) -> dolly::transform::Transform {
        self.rig.update(params.delta_time_seconds)
    }

    fn as_any_mut(&mut self) -> &mut dyn std::any::Any {
        self
    }
}
```

And while it's more spammy, there's no implicit access to a field named `rig` here as the macro has right now. I personally only don't like having the `as_any_mut` here, but we can factor that out with some trait changes. Here's a quick stab at that, plus a sliiiiiightly tweaked version of your example: https://github.com/h3r2tic/dolly/compare/kick-out-asanymut

---

The `LockPosition` and `LockRotation` stuff seems quite useful! My main nitpicks there would be that the axis locking configuration can probably be done with just three bools (one per axis) instead of arrays, which _I think_ would be easier to work with (especially if you want to change the locking at runtime), and not require the `'static` lifetime references.

I think the rotation locking should also be doable by clearing the `Quat` `x`, `y`, and `z` fields, and re-normalizing the quaternion, but would need to test things to make sure I'm not being silly with my understanding of quaternions (and that would likely need extra care if all three axes of the quaternion become zero). I believe the proposed axis-angle variant will behave in a somewhat odd way since it will try to preserve the rotation angle, including the part of rotation around the axis being removed.

**Comment by BlackPhlox** [comment]
Happy holidays! Per our discussion, I've removed the `lock_rotation` driver and moved it to a `lock_rot` branch [here](https://github.com/BlackPhlox/dolly/tree/lock_rot). The `follow.rs` example is now instead controllable using WASD to move either the player or camera.

**Comment by h3r2tic** [comment]
Very cool, and neat example! Took me a bit to get used to the controls and realize what's happening -- the lack of shadows in the sample is not helping 😅 Might need to switch to some other renderer to make the samples clearer. Nevertheless, nicely done!

I'll do a bit of a clean-up of the `follow.rs` sample (with some comments and stuff) in another commit.

**Comment by h3r2tic** [comment]
https://github.com/h3r2tic/dolly/commit/47a47a47288b407d75620b773aab110bcfce0638

I've removed the rotation and the arm from the camera, and did some minor cleanup of the runtime code (such as breaking out the input -> movement calculation to its own function).

The rotation was not being used (and if it was, the arm would rotate with it, looking rather funny). The arm was redundant with positioning of the camera. Perhaps those make sense in the context of a larger sample, where they're also being driven, but here it was better to simplify.

Hope this makes sense 🙂

**Comment by h3r2tic** [comment]
Oh yeah, and I've released `0.2` with this 🥳. The user-facing traits have changed, so figured this was a potentially breaking change.

**Comment by BlackPhlox** [comment]
Yay! 🎉 I totally agree with simplifying examples (be explicit) as much as possible (also with the rename). Yeah, that trait might be a breaking change for some. Thanks!

**Comment by h3r2tic** [comment]
Yay, happy to hear ❤️

**Pull request merged**
